---
- name: Create before_backup script
  template: src=before_backup.j2 dest=/usr/libexec/bacula/before_backup
          owner=root group=root mode=0755
- name: Create after_backup script
  template: src=after_backup.j2 dest=/usr/libexec/bacula/after_backup
          owner=root group=root mode=0755
